# ===================================================================
# Módulo A — Servicio de Identidad y Autenticación
# ===================================================================

# 1. Puerto HTTP (8081 por defecto para Módulo A)
quarkus.http.port=${PORT:8081}

# 2. Configuración de PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:labcom,2015}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/tesis_db}

# Generación y sincronización de tablas Hibernate / Panache
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# 3. Integración con APIs Externas (CA Simulator / Registro Civil)
signature-api/mp-rest/url=${SIGNATURE_SERVICE_URL:https://simulador-ca-ecuador-dhb6b2h9gbc6e2a2.eastus-01.azurewebsites.net/}
identity-api/mp-rest/url=${IDENTITY_SERVICE_URL:https://api-simulacion-registro-civil-evbgdua8hvgpfkht.eastus-01.azurewebsites.net}

# 4. Azure Key Vault & Master Key
quarkus.azure.keyvault.url=${AZURE_VAULT_URL:https://tesis-forensic-vault.vault.azure.net/}
tesis.master-key.name=${MASTER_KEY_NAME:master-custody-key}
quarkus.devservices.enabled=false

# 5. Configuración de Límite de carga de archivos multipart
quarkus.http.limits.max-body-size=500M
