# 1. Configuración de PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/tesis_db

# 2. Generación automática de tablas (Factor IV: Backing Services)
# Esto creará la tabla "usuarios" automáticamente al arrancar
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# API 1: Registro Civil
identity-api/mp-rest/url=https://api-simulacion-registro-civil-evbgdua8hvgpfkht.eastus-01.azurewebsites.net

# API 2: Validador de Firmas (Tu nueva Azure Function)
signature-api/mp-rest/url=https://simulador-ca-ecuador-dhb6b2h9gbc6e2a2.eastus-01.azurewebsites.net/

# el tiempo de espera
quarkus.vertx.warning-exception-time=30s